### ISSUE TITLE
Inconsistency in git config option name

### ISSUE THREAD

**Issue by laitdebanane** [bddenhartog/git-profiles#4]
# Issue

In the projects `README.md` file, it is said the user needs to edit their global git configuration with commands like these:

```bash
# Lines 108 to 110 at time of writing
git config --global --add profile.path /code/office
git config --global --add profile.path /code/personal
git config --global --add profile.path /code/client
```

However, the `git-profiles.sh` script uses the following command to read the edited global git configuration:

```bash
# Line 26 at time of writing
local locations="${GIT_PROFILES_GIT_COMMAND} config --global --get-all profiles.path"
```

Notice the inconsistency in option naming: `profile.path` in the README and `profiles.path` in the script.

This looks like a simple oversight in the documentation, but makes it so that users that don't read the actual code are not able to make this (useful) tool work.

# Potential fixes

* Edit the README to reflect the correct git configuration name to use.
* Edit the script to use `profile.path` instead of `profiles.path` (not backwards-compatible).

# Retroactive fix for previous users

What I did was edit my `~/.gitconfig` file by changing `[profile]` to `[profiles]`. Whether this is the way to go depends on what fix is applied to this problem.

**Comment by bddenhartog** [comment]
I'm glad you find `git-profiles` useful! I haven't ever actually had a need for it, which is probably why this pretty clear-cut issue hasn't been discovered earlier. Thanks for bringing this to my attention!

I'll refactor the `README` to update the command users should execute when adding profiles.
